/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type EditorialPage = {
  _id: string;
  _type: "editorialPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  pageId:
    | "home"
    | "about"
    | "values"
    | "for-artists"
    | "pilot"
    | "support"
    | "contact"
    | "instagram";
  eyebrow?: string;
  title: string;
  lede: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  secondaryTitle?: string;
  secondaryBody?: string;
  items?: Array<
    {
      _key: string;
    } & CopyBlock
  >;
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question: string;
  answer: string;
  group: "artists" | "contact" | "values";
  order?: number;
};

export type Value = {
  _id: string;
  _type: "value";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  body: string;
  order?: number;
};

export type Resource = {
  _id: string;
  _type: "resource";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  category: string;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  summary: string;
  body: string;
  publishedAt?: string;
  featured?: boolean;
  seo?: Seo;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type ArtistReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "artist";
};

export type Artwork = {
  _id: string;
  _type: "artwork";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  artist: ArtistReference;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  year?: number;
  medium: string;
  dimensions?: string;
  description?: string;
  purchaseUrl?: string;
  featured?: boolean;
};

export type Artist = {
  _id: string;
  _type: "artist";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  portrait: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  shortBio: string;
  bio: string;
  city: string;
  region: "NS" | "NB" | "PE" | "NL";
  disciplines: Array<string>;
  website?: string;
  instagramUrl?: string;
  featured?: boolean;
  seo?: Seo;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName: string;
  tagline?: string;
  description: string;
  contactEmail?: string;
  instagramUrl?: string;
  seo?: Seo;
};

export type CopyBlock = {
  _type: "copyBlock";
  title: string;
  body: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | EditorialPage
  | Seo
  | SanityImageCrop
  | SanityImageHotspot
  | Faq
  | Value
  | Resource
  | Slug
  | ArtistReference
  | Artwork
  | Artist
  | SiteSettings
  | CopyBlock
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/queries/index.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0] {    siteName,    tagline,    description,    contactEmail,    instagramUrl,    seo {      title,      description,      image {   asset,  hotspot,  crop,  alt }    }  }
export type SiteSettingsQueryResult = {
  siteName: string;
  tagline: string | null;
  description: string;
  contactEmail: string | null;
  instagramUrl: string | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: null;
    } | null;
  } | null;
} | null;

// Source: sanity/queries/index.ts
// Variable: artistsQuery
// Query: *[_type == "artist" && defined(slug.current)] | order(name asc) {    _id,    name,    "slug": slug.current,    shortBio,    city,    region,    disciplines,    featured,    portrait {   asset,  hotspot,  crop,  alt }  }
export type ArtistsQueryResult = Array<{
  _id: string;
  name: string;
  slug: string;
  shortBio: string;
  city: string;
  region: "NB" | "NL" | "NS" | "PE";
  disciplines: Array<string>;
  featured: boolean | null;
  portrait: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string;
  };
}>;

// Source: sanity/queries/index.ts
// Variable: artistSlugsQuery
// Query: *[_type == "artist" && defined(slug.current)] {    "slug": slug.current  }
export type ArtistSlugsQueryResult = Array<{
  slug: string;
}>;

// Source: sanity/queries/index.ts
// Variable: artistBySlugQuery
// Query: *[_type == "artist" && slug.current == $slug][0] {    _id,    name,    "slug": slug.current,    shortBio,    bio,    city,    region,    disciplines,    website,    instagramUrl,    featured,    portrait {   asset,  hotspot,  crop,  alt },    seo {      title,      description,      image {   asset,  hotspot,  crop,  alt }    },    "artworks": *[_type == "artwork" && artist._ref == ^._id] | order(year desc, title asc) {      _id,      title,      "slug": slug.current,      year,      medium,      dimensions,      description,      purchaseUrl,      featured,      image {   asset,  hotspot,  crop,  alt }    }  }
export type ArtistBySlugQueryResult = {
  _id: string;
  name: string;
  slug: string;
  shortBio: string;
  bio: string;
  city: string;
  region: "NB" | "NL" | "NS" | "PE";
  disciplines: Array<string>;
  website: string | null;
  instagramUrl: string | null;
  featured: boolean | null;
  portrait: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string;
  };
  seo: {
    title: string | null;
    description: string | null;
    image: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: null;
    } | null;
  } | null;
  artworks: Array<{
    _id: string;
    title: string;
    slug: string;
    year: number | null;
    medium: string;
    dimensions: string | null;
    description: string | null;
    purchaseUrl: string | null;
    featured: boolean | null;
    image: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: string;
    };
  }>;
} | null;

// Source: sanity/queries/index.ts
// Variable: artworksQuery
// Query: *[_type == "artwork" && defined(slug.current)] | order(year desc, title asc) {    _id,    title,    "slug": slug.current,    year,    medium,    dimensions,    description,    purchaseUrl,    featured,    image {   asset,  hotspot,  crop,  alt },    artist->{      _id,      name,      "slug": slug.current    }  }
export type ArtworksQueryResult = Array<{
  _id: string;
  title: string;
  slug: string;
  year: number | null;
  medium: string;
  dimensions: string | null;
  description: string | null;
  purchaseUrl: string | null;
  featured: boolean | null;
  image: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string;
  };
  artist: {
    _id: string;
    name: string;
    slug: string;
  };
}>;

// Source: sanity/queries/index.ts
// Variable: featuredArtworksQuery
// Query: *[_type == "artwork" && featured == true && defined(slug.current)] | order(year desc, title asc) {    _id,    title,    "slug": slug.current,    year,    medium,    dimensions,    description,    purchaseUrl,    featured,    image {   asset,  hotspot,  crop,  alt },    artist->{      _id,      name,      "slug": slug.current    }  }
export type FeaturedArtworksQueryResult = Array<{
  _id: string;
  title: string;
  slug: string;
  year: number | null;
  medium: string;
  dimensions: string | null;
  description: string | null;
  purchaseUrl: string | null;
  featured: true;
  image: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string;
  };
  artist: {
    _id: string;
    name: string;
    slug: string;
  };
}>;

// Source: sanity/queries/index.ts
// Variable: resourcesQuery
// Query: *[_type == "resource" && defined(slug.current)] | order(coalesce(publishedAt, _createdAt) desc) {    _id,    title,    "slug": slug.current,    category,    summary,    featured,    image {   asset,  hotspot,  crop,  alt }  }
export type ResourcesQueryResult = Array<{
  _id: string;
  title: string;
  slug: string;
  category: string;
  summary: string;
  featured: boolean | null;
  image: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string;
  };
}>;

// Source: sanity/queries/index.ts
// Variable: resourceSlugsQuery
// Query: *[_type == "resource" && defined(slug.current)] {    "slug": slug.current  }
export type ResourceSlugsQueryResult = Array<{
  slug: string;
}>;

// Source: sanity/queries/index.ts
// Variable: resourceBySlugQuery
// Query: *[_type == "resource" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    category,    summary,    body,    publishedAt,    featured,    image {   asset,  hotspot,  crop,  alt },    seo {      title,      description,      image {   asset,  hotspot,  crop,  alt }    }  }
export type ResourceBySlugQueryResult = {
  _id: string;
  title: string;
  slug: string;
  category: string;
  summary: string;
  body: string;
  publishedAt: string | null;
  featured: boolean | null;
  image: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string;
  };
  seo: {
    title: string | null;
    description: string | null;
    image: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: null;
    } | null;
  } | null;
} | null;

// Source: sanity/queries/index.ts
// Variable: valuesQuery
// Query: *[_type == "value"] | order(order asc, title asc) {    _id,    title,    body,    order  }
export type ValuesQueryResult = Array<{
  _id: string;
  title: string;
  body: string;
  order: number | null;
}>;

// Source: sanity/queries/index.ts
// Variable: faqsByGroupQuery
// Query: *[_type == "faq" && group == $group] | order(order asc, question asc) {    _id,    question,    answer,    group,    order  }
export type FaqsByGroupQueryResult = Array<{
  _id: string;
  question: string;
  answer: string;
  group: "artists" | "contact" | "values";
  order: number | null;
}>;

// Source: sanity/queries/index.ts
// Variable: editorialPageQuery
// Query: *[_type == "editorialPage" && pageId == $pageId][0] {    _id,    pageId,    eyebrow,    title,    lede,    secondaryTitle,    secondaryBody,    items[] {      title,      body    },    image {   asset,  hotspot,  crop,  alt },    seo {      title,      description,      image {   asset,  hotspot,  crop,  alt }    }  }
export type EditorialPageQueryResult = {
  _id: string;
  pageId:
    | "about"
    | "contact"
    | "for-artists"
    | "home"
    | "instagram"
    | "pilot"
    | "support"
    | "values";
  eyebrow: string | null;
  title: string;
  lede: string;
  secondaryTitle: string | null;
  secondaryBody: string | null;
  items: Array<{
    title: string;
    body: string;
  }> | null;
  image: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
  } | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: null;
    } | null;
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "siteSettings" && _id == "siteSettings"][0] {\n    siteName,\n    tagline,\n    description,\n    contactEmail,\n    instagramUrl,\n    seo {\n      title,\n      description,\n      image { \n  asset,\n  hotspot,\n  crop,\n  alt\n }\n    }\n  }\n': SiteSettingsQueryResult;
    '\n  *[_type == "artist" && defined(slug.current)] | order(name asc) {\n    _id,\n    name,\n    "slug": slug.current,\n    shortBio,\n    city,\n    region,\n    disciplines,\n    featured,\n    portrait { \n  asset,\n  hotspot,\n  crop,\n  alt\n }\n  }\n': ArtistsQueryResult;
    '\n  *[_type == "artist" && defined(slug.current)] {\n    "slug": slug.current\n  }\n': ArtistSlugsQueryResult;
    '\n  *[_type == "artist" && slug.current == $slug][0] {\n    _id,\n    name,\n    "slug": slug.current,\n    shortBio,\n    bio,\n    city,\n    region,\n    disciplines,\n    website,\n    instagramUrl,\n    featured,\n    portrait { \n  asset,\n  hotspot,\n  crop,\n  alt\n },\n    seo {\n      title,\n      description,\n      image { \n  asset,\n  hotspot,\n  crop,\n  alt\n }\n    },\n    "artworks": *[_type == "artwork" && artist._ref == ^._id] | order(year desc, title asc) {\n      _id,\n      title,\n      "slug": slug.current,\n      year,\n      medium,\n      dimensions,\n      description,\n      purchaseUrl,\n      featured,\n      image { \n  asset,\n  hotspot,\n  crop,\n  alt\n }\n    }\n  }\n': ArtistBySlugQueryResult;
    '\n  *[_type == "artwork" && defined(slug.current)] | order(year desc, title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    year,\n    medium,\n    dimensions,\n    description,\n    purchaseUrl,\n    featured,\n    image { \n  asset,\n  hotspot,\n  crop,\n  alt\n },\n    artist->{\n      _id,\n      name,\n      "slug": slug.current\n    }\n  }\n': ArtworksQueryResult;
    '\n  *[_type == "artwork" && featured == true && defined(slug.current)] | order(year desc, title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    year,\n    medium,\n    dimensions,\n    description,\n    purchaseUrl,\n    featured,\n    image { \n  asset,\n  hotspot,\n  crop,\n  alt\n },\n    artist->{\n      _id,\n      name,\n      "slug": slug.current\n    }\n  }\n': FeaturedArtworksQueryResult;
    '\n  *[_type == "resource" && defined(slug.current)] | order(coalesce(publishedAt, _createdAt) desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    category,\n    summary,\n    featured,\n    image { \n  asset,\n  hotspot,\n  crop,\n  alt\n }\n  }\n': ResourcesQueryResult;
    '\n  *[_type == "resource" && defined(slug.current)] {\n    "slug": slug.current\n  }\n': ResourceSlugsQueryResult;
    '\n  *[_type == "resource" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    category,\n    summary,\n    body,\n    publishedAt,\n    featured,\n    image { \n  asset,\n  hotspot,\n  crop,\n  alt\n },\n    seo {\n      title,\n      description,\n      image { \n  asset,\n  hotspot,\n  crop,\n  alt\n }\n    }\n  }\n': ResourceBySlugQueryResult;
    '\n  *[_type == "value"] | order(order asc, title asc) {\n    _id,\n    title,\n    body,\n    order\n  }\n': ValuesQueryResult;
    '\n  *[_type == "faq" && group == $group] | order(order asc, question asc) {\n    _id,\n    question,\n    answer,\n    group,\n    order\n  }\n': FaqsByGroupQueryResult;
    '\n  *[_type == "editorialPage" && pageId == $pageId][0] {\n    _id,\n    pageId,\n    eyebrow,\n    title,\n    lede,\n    secondaryTitle,\n    secondaryBody,\n    items[] {\n      title,\n      body\n    },\n    image { \n  asset,\n  hotspot,\n  crop,\n  alt\n },\n    seo {\n      title,\n      description,\n      image { \n  asset,\n  hotspot,\n  crop,\n  alt\n }\n    }\n  }\n': EditorialPageQueryResult;
  }
}
