/** Development catalog: invented Atlantic makers with niches and bodies of work. */

function unsplash(id) {
  return `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1600&q=80`;
}

export const artists = [
  {
    _id: "artist.mira",
    name: "Mira Chiasson",
    slug: "mira-chiasson",
    city: "Halifax",
    region: "NS",
    disciplines: ["ceramics"],
    featured: true,
    website: "https://example.com/mira",
    instagramUrl: "https://www.instagram.com/",
    shortBio:
      "Coil-built kitchen ware from a backyard kiln in the North End. Stew pots and everyday cups meant to be used hard.",
    bio: `Mira works clay through the week in a shared Dartmouth studio and fires on weekends in a brick kiln behind a North End house that is not quite hers.

The work is meant to be used — soup, flowers, the odd leftover — and to hold a bit of the neighbourhood in the clay. She titles pieces after streets that no longer exist under those names, then writes the old name on the foot in pencil so it survives the glaze but not the dishwasher.

She exhibits rarely. She answers email slowly. The kiln is louder than she is.`,
    portraitKey: "portrait-mira",
    portraitAlt:
      "A person with dark hair looking slightly off camera, photographed outdoors",
    seo: {
      title: "Mira Chiasson — Ceramics",
      description:
        "Coil-built vessels and backyard firings from Halifax, Nova Scotia.",
    },
  },
  {
    _id: "artist.emile",
    name: "Émile LeBlanc",
    slug: "emile-leblanc",
    city: "Dieppe",
    region: "NB",
    disciplines: ["glass"],
    featured: true,
    website: "https://example.com/emile",
    shortBio:
      "Blown vessels that catch kitchen light. Thin walls, thick feet, colours named after weather.",
    bio: `Émile works a torch and a glory hole in a shared shop off Acadie Avenue. He talks about viscosity the way other people talk about dough.

Nothing leaves the bench until it can stand up to a dishwasher. The colours come from weather reports he keeps taped above the annealer — fog, squall, clear, and the rare red sky that means nothing good for anyone out on the water.`,
    portraitKey: "portrait-emile",
    portraitAlt: "Portrait of a person standing in open daylight",
  },
  {
    _id: "artist.jo",
    name: "Jo MacNeil",
    slug: "jo-macneil",
    city: "Sydney",
    region: "NS",
    disciplines: ["wood"],
    featured: false,
    shortBio:
      "Salvaged maple turned into spoons and small stools. Tools you actually use, finished by hand.",
    bio: `Jo carves spoons and builds small stools from maple that would otherwise become firewood. The shop is a lean-to off a Cape Breton kitchen.

Names stay short. Descriptions stay shorter. If it holds soup or holds a person, it is finished.`,
    portraitKey: "portrait-jo",
    portraitAlt: "Close portrait of a person with short hair and a wool sweater",
  },
  {
    _id: "artist.sam",
    name: "Sam Okonkwo",
    slug: "sam-okonkwo",
    city: "Fredericton",
    region: "NB",
    disciplines: ["illustration"],
    featured: false,
    instagramUrl: "https://www.instagram.com/",
    shortBio:
      "Ink drawings of buses, kitchens, and the particular boredom of a Saturday in town.",
    bio: `Sam draws on leftover print proofs and grocery receipts when the good paper runs out. The work is funny without being mean, and detailed without asking you to squint.

Saturday is the recurring subject — the bus that never quite empties, the rink lobby at noon, the kitchen after everyone has left their mugs.`,
    portraitKey: "portrait-sam",
    portraitAlt: "Portrait of a person against a dark background",
  },
  {
    _id: "artist.river",
    name: "River Quinn",
    slug: "river-quinn",
    city: "St. John's",
    region: "NL",
    disciplines: ["collage"],
    featured: false,
    shortBio:
      "Cut-paper rooms assembled from seed catalogues and ferry tickets. Interiors that already happened.",
    bio: `River treats the island as a scrapbook that already happened. Ferry stubs, seed catalogues, and the odd church bulletin become rooms you could almost walk into.

Nothing is glued until it has been moved at least three times. The work stays flat; the rooms do not.`,
    portraitKey: "portrait-river",
    portraitAlt: "Portrait of a person with hair pulled back, facing the camera",
  },
  {
    _id: "artist.hannah",
    name: "Hannah Proudfoot",
    slug: "hannah-proudfoot",
    city: "Charlottetown",
    region: "PE",
    disciplines: ["painting"],
    featured: false,
    website: "https://example.com/hannah",
    shortBio:
      "North Shore weather in oil, then the kitchen after. Shoreline canvases and quiet winter interiors.",
    bio: `Hannah paints the North Shore until the light changes, then brings the same palette indoors. The shoreline set is wind and tide; the winter interiors are the kettle and the chair that faces the window.

She works small enough to finish in a week and large enough that the weather still has room to sit.`,
    portraitKey: "portrait-hannah",
    portraitAlt: "Portrait of a person near a window, soft daylight",
  },
  {
    _id: "artist.kofi",
    name: "Kofi Mensah",
    slug: "kofi-mensah",
    city: "St. John's",
    region: "NL",
    disciplines: ["photography"],
    featured: false,
    shortBio:
      "Analogue harbour nights. Gelatin silver prints made after the boats come in.",
    bio: `Kofi shoots film after the harbour empties. The darkroom is a bathroom with the window taped shut. Prints are small, silver, and wet longer than they should be.

He titles by the hour, not the boat. The work is about what remains when the engines stop.`,
    portraitKey: "portrait-kofi",
    portraitAlt: "Portrait of a person outdoors in cool light",
  },
  {
    _id: "artist.sable",
    name: "Sable Hart",
    slug: "sable-hart",
    city: "Lunenburg",
    region: "NS",
    disciplines: ["textiles"],
    featured: false,
    instagramUrl: "https://www.instagram.com/",
    shortBio:
      "Local fleece and plant dye. Bed blankets you sleep under and wall weavings you look at.",
    bio: `Sable spins and dyes fleece from flocks within an hour of Lunenburg. Bed blankets leave the loom soft enough to use; wall weavings stay stiff enough to hang.

Plant dye means patience and a notebook of failed greens. The colour that sticks is rarely the one she meant.`,
    portraitKey: "portrait-sable",
    portraitAlt: "Portrait of a person in natural light, soft background",
  },
  {
    _id: "artist.noor",
    name: "Noor Rahman",
    slug: "noor-rahman",
    city: "Saint John",
    region: "NB",
    disciplines: ["jewelry"],
    featured: false,
    website: "https://example.com/noor",
    shortBio:
      "Sterling and Fundy beach stones. A shoreline set made for everyday wear.",
    bio: `Noor walks the Fundy shore for stones that already look finished, then sets them in sterling that does not pretend to be precious.

The shoreline set is meant for hands that work — rings that survive dishwashing, pendants that sit flat under a sweater.`,
    portraitKey: "portrait-noor",
    portraitAlt: "Portrait of a person facing the camera, calm expression",
  },
  {
    _id: "artist.ellis",
    name: "Ellis Park",
    slug: "ellis-park",
    city: "Halifax",
    region: "NS",
    disciplines: ["printmaking"],
    featured: false,
    shortBio:
      "Linocut editions of backyard birds and the supper table. Small runs, cotton rag, ink still wet in the corners.",
    bio: `Ellis cuts linoleum in a North End basement and prints on cotton rag when the press is free. Backyard birds came first; the supper table followed when the birds ran out of poses.

Editions stay under twenty. Numbering is careful. Signing is the last thing before the stack leaves the table.`,
    portraitKey: "portrait-ellis",
    portraitAlt: "Portrait of a person in a workshop setting",
  },
  {
    _id: "artist.wren",
    name: "Wren Callahan",
    slug: "wren-callahan",
    city: "Sackville",
    region: "NB",
    disciplines: ["sculpture", "mixed-media"],
    featured: false,
    shortBio:
      "Driftwood, steel, and the odd photo transfer. Garden sculptures and mixed panels from the Tantramar.",
    bio: `Wren builds in a barn on the edge of the marsh. Garden sculptures stand in mud until they earn a wall; mixed panels combine wood, steel, and transfers from old photographs found at the dump.

Nothing is precious. Everything is weighted so the wind does not take it.`,
    portraitKey: "portrait-wren",
    portraitAlt: "Portrait of a person outdoors against a soft landscape",
  },
  {
    _id: "artist.maeve",
    name: "Maeve O'Shea",
    slug: "maeve-oshea",
    city: "Summerside",
    region: "PE",
    disciplines: ["textiles"],
    featured: true,
    website: "https://example.com/maeve",
    shortBio:
      "Island fleece woven into bed runners and wall hangings. Plant dye, slow colour, Summerside light.",
    bio: `Maeve spins fleece from Island flocks and dyes with what the hedgerow gives up. Bed runners leave the loom soft enough for a guest bed; wall hangings stay stiff enough to hold a room.

Summerside is quieter than Charlottetown for a reason. She likes that. The work takes the weather seriously and the calendar lightly.`,
    portraitKey: "portrait-maeve",
    portraitAlt: "Portrait of a person with wind-caught hair outdoors",
  },
  {
    _id: "artist.tessa",
    name: "Tessa Gallant",
    slug: "tessa-gallant",
    city: "Montague",
    region: "PE",
    disciplines: ["ceramics"],
    featured: false,
    shortBio:
      "Salt-glaze jars and garden pots from a Montague kiln. Kitchen storage that can live outside.",
    bio: `Tessa fires salt-glaze on weekends and stacks pots in a shed that used to hold lobster traps. The jars are for flour and beans; the garden pots are for whatever survives a PEI spring.

She does not chase thin porcelain. She chases a surface that looks like it weathered the Strait.`,
    portraitKey: "portrait-tessa",
    portraitAlt: "Portrait of a person in soft outdoor light",
  },
  {
    _id: "artist.owen",
    name: "Owen Brake",
    slug: "owen-brake",
    city: "Corner Brook",
    region: "NL",
    disciplines: ["wood"],
    featured: false,
    shortBio:
      "Chairs and cutting boards from western Newfoundland maple. Built to sit on and slice on.",
    bio: `Owen works maple that came down in ice storms and still has something to say. Chairs get three coats of oil. Cutting boards get one and a promise they will scar honestly.

Corner Brook is far enough from St. John's that the wood feels local without needing a ferry story.`,
    portraitKey: "portrait-owen",
    portraitAlt: "Portrait of a person in a workshop sweater",
  },
  {
    _id: "artist.isla",
    name: "Isla Barron",
    slug: "isla-barron",
    city: "Twillingate",
    region: "NL",
    disciplines: ["painting"],
    featured: true,
    instagramUrl: "https://www.instagram.com/",
    shortBio:
      "Harbour nights and whale-watch weather in oil. Twillingate light, painted before it leaves.",
    bio: `Isla paints the harbour after the day boats are in and the icebergs are still deciding. The whale-watch canvases are faster — weather that will not sit still for a second pass.

She keeps the studio cold on purpose. Warm rooms make the oil too friendly.`,
    portraitKey: "portrait-isla",
    portraitAlt: "Portrait of a person against a cool outdoor backdrop",
  },
  {
    _id: "artist.priya",
    name: "Priya Desai",
    slug: "priya-desai",
    city: "Moncton",
    region: "NB",
    disciplines: ["illustration"],
    featured: false,
    shortBio:
      "Ink of market stalls and apartment windows. Ordinary Moncton, drawn like it matters.",
    bio: `Priya draws the Saturday market before the good vegetables are gone, and the apartment windows that face the wrong way for sunset. The ink is dry; the humour is not mean.

She works small so a page can finish in an evening. Editions are not the point. Looking is.`,
    portraitKey: "portrait-priya",
    portraitAlt: "Portrait of a person facing the camera indoors",
  },
  {
    _id: "artist.malik",
    name: "Malik Torres",
    slug: "malik-torres",
    city: "Halifax",
    region: "NS",
    disciplines: ["photography"],
    featured: false,
    website: "https://example.com/malik",
    shortBio:
      "Street markets and night buses on film. Halifax after the tourists leave the frame.",
    bio: `Malik shoots markets when the light is unkind and buses when everyone is tired enough to be honest. The darkroom is shared. The prints are small.

He titles by the stop or the stall, not the feeling. The feeling is your job.`,
    portraitKey: "portrait-malik",
    portraitAlt: "Portrait of a person in urban daylight",
  },
  {
    _id: "artist.cass",
    name: "Cass Fournier",
    slug: "cass-fournier",
    city: "Digby",
    region: "NS",
    disciplines: ["sculpture"],
    featured: false,
    shortBio:
      "Harbour steel and drift forms. Sculpture weighted for Fundy wind, not for a white cube.",
    bio: `Cass welds and binds in a shed that smells like tide. Harbour steel pieces stand where trucks turn around; drift forms are quieter but still heavy enough that the wind loses.

Nothing is precious. Everything is bolted or buried until it earns a plinth.`,
    portraitKey: "portrait-cass",
    portraitAlt: "Portrait of a person outdoors near water",
  },
  {
    _id: "artist.yuki",
    name: "Yuki Tanaka",
    slug: "yuki-tanaka",
    city: "Fredericton",
    region: "NB",
    disciplines: ["jewelry"],
    featured: false,
    shortBio:
      "River-stone jewelry and everyday bands. Sterling made for hands that wash dishes.",
    bio: `Yuki walks the river for stones that already look finished, then sets them so rings survive dishwashing and pendants sit flat under a sweater.

Fredericton is small enough that people notice when you wear the work. She likes that pressure.`,
    portraitKey: "portrait-yuki",
    portraitAlt: "Portrait of a person with a calm expression",
  },
  {
    _id: "artist.rowan",
    name: "Rowan Vale",
    slug: "rowan-vale",
    city: "Antigonish",
    region: "NS",
    disciplines: ["collage", "printmaking"],
    featured: false,
    shortBio:
      "Ticket collages and small linocut runs. Paper that has already been somewhere.",
    bio: `Rowan cuts tickets and ferry stubs into rooms, then prints small linocut editions when the press is free. The collage is restless; the prints are numbered and calm.

Antigonish keeps both practices within walking distance of a kettle.`,
    portraitKey: "portrait-rowan",
    portraitAlt: "Portrait of a person in soft indoor light",
  },
];

export const artworks = [
  // Mira — stew vessels
  {
    _id: "artwork.january-vessel",
    title: "January Vessel",
    slug: "january-vessel",
    artistId: "artist.mira",
    year: 2025,
    medium: "Stoneware, ash glaze",
    dimensions: "28 × 22 × 22 cm",
    featured: true,
    description: "Fired during the cold snap. Wide mouth, quiet foot, meant for stew.",
    purchaseUrl: "https://example.com/shop/january-vessel",
    imageKey: "work-ceramic-1",
    imageAlt: "A wide ceramic vessel on a wooden table",
  },
  {
    _id: "artwork.north-end-bowl",
    title: "North End Bowl",
    slug: "north-end-bowl",
    artistId: "artist.mira",
    year: 2024,
    medium: "Hand-built stoneware",
    featured: false,
    description: "A breakfast bowl that still has the seam of the coil inside.",
    imageKey: "work-ceramic-2",
    imageAlt: "A tall ceramic form photographed against a wall",
  },
  {
    _id: "artwork.winter-pourer",
    title: "Winter Pourer",
    slug: "winter-pourer",
    artistId: "artist.mira",
    year: 2025,
    medium: "Wheel-thrown pitcher",
    dimensions: "variable",
    featured: false,
    imageKey: "work-ceramic-3",
    imageAlt: "A ceramic pitcher photographed close",
  },
  // Mira — everyday cups
  {
    _id: "artwork.tuesday-cup",
    title: "Tuesday Cup",
    slug: "tuesday-cup",
    artistId: "artist.mira",
    year: 2026,
    medium: "Porcelain, clear glaze",
    dimensions: "9 × 8 cm",
    featured: false,
    description: "Thin rim, thick foot. Named for the day it left the kiln.",
    imageKey: "work-ceramic-4",
    imageAlt: "A ceramic cup on a table in soft light",
  },
  {
    _id: "artwork.alley-mug",
    title: "Alley Mug",
    slug: "alley-mug",
    artistId: "artist.mira",
    year: 2024,
    medium: "Stoneware, ash glaze",
    featured: false,
    imageKey: "work-ceramic-1",
    imageAlt: "A ceramic mug with a wide handle",
  },
  {
    _id: "artwork.fold-cup",
    title: "Fold Cup",
    slug: "fold-cup",
    artistId: "artist.mira",
    year: 2023,
    medium: "Hand-built stoneware",
    featured: false,
    description: "A crease left on purpose where the coil met itself.",
    imageKey: "work-ceramic-2",
    imageAlt: "A handmade ceramic cup with a visible seam",
  },

  // Émile — kitchen glass
  {
    _id: "artwork.weather-glass",
    title: "Weather Glass",
    slug: "weather-glass",
    artistId: "artist.emile",
    year: 2025,
    medium: "Blown glass",
    featured: true,
    description: "Sea-green, thick foot, thin enough to sing if you wet the rim.",
    imageKey: "work-glass-1",
    imageAlt: "A tall glass vessel catching window light",
  },
  {
    _id: "artwork.fog-bowl",
    title: "Fog Bowl",
    slug: "fog-bowl",
    artistId: "artist.emile",
    year: 2023,
    medium: "Blown glass",
    featured: false,
    imageKey: "work-glass-2",
    imageAlt: "A pale glass bowl on a windowsill",
  },
  {
    _id: "artwork.squall-tumbler",
    title: "Squall Tumbler",
    slug: "squall-tumbler",
    artistId: "artist.emile",
    year: 2026,
    medium: "Blown glass",
    dimensions: "12 × 8 cm",
    featured: false,
    description: "Grey-blue, dishwasher-safe, named for a March forecast.",
    imageKey: "work-glass-3",
    imageAlt: "A glass tumbler on a kitchen counter",
  },
  {
    _id: "artwork.clear-carafe",
    title: "Clear Carafe",
    slug: "clear-carafe",
    artistId: "artist.emile",
    year: 2024,
    medium: "Blown glass",
    featured: false,
    imageKey: "work-glass-1",
    imageAlt: "A clear glass carafe with a thick base",
  },

  // Jo — spoons + stools
  {
    _id: "artwork.kitchen-spoon",
    title: "Kitchen Spoon",
    slug: "kitchen-spoon",
    artistId: "artist.jo",
    year: 2025,
    medium: "Salvaged maple",
    featured: false,
    description: "One piece. No varnish. Meant for soup.",
    imageKey: "work-wood-1",
    imageAlt: "A wooden spoon on a workbench",
  },
  {
    _id: "artwork.stirring-spoon",
    title: "Stirring Spoon",
    slug: "stirring-spoon",
    artistId: "artist.jo",
    year: 2024,
    medium: "Salvaged maple",
    featured: false,
    imageKey: "work-wood-2",
    imageAlt: "A long wooden spoon carved from maple",
  },
  {
    _id: "artwork.storm-stool",
    title: "Storm Stool",
    slug: "storm-stool",
    artistId: "artist.jo",
    year: 2023,
    medium: "Salvaged maple",
    featured: false,
    description: "Three legs. Built during a power outage.",
    imageKey: "work-wood-3",
    imageAlt: "A wooden stool in a workshop",
  },
  {
    _id: "artwork.porch-stool",
    title: "Porch Stool",
    slug: "porch-stool",
    artistId: "artist.jo",
    year: 2026,
    medium: "Salvaged maple",
    featured: false,
    imageKey: "work-wood-3",
    imageAlt: "A small wooden stool outdoors",
  },
  {
    _id: "artwork.ladle",
    title: "Ladle",
    slug: "ladle",
    artistId: "artist.jo",
    year: 2022,
    medium: "Carved maple",
    featured: false,
    imageKey: "work-wood-1",
    imageAlt: "A carved wooden ladle",
  },

  // Sam — Saturday drawings
  {
    _id: "artwork.saturday-bus",
    title: "Saturday Bus",
    slug: "saturday-bus",
    artistId: "artist.sam",
    year: 2025,
    medium: "Ink illustration on paper",
    featured: false,
    description: "Everyone looking at their phones except the one person who is not.",
    imageKey: "work-ink-1",
    imageAlt: "An ink drawing photographed as a vertical page",
  },
  {
    _id: "artwork.rink-lobby",
    title: "Rink Lobby",
    slug: "rink-lobby",
    artistId: "artist.sam",
    year: 2024,
    medium: "Ink drawing",
    featured: false,
    imageKey: "work-ink-2",
    imageAlt: "An ink drawing of an indoor public space",
  },
  {
    _id: "artwork.kitchen-after",
    title: "Kitchen After",
    slug: "kitchen-after",
    artistId: "artist.sam",
    year: 2026,
    medium: "Ink illustration on paper",
    featured: false,
    description: "Three mugs. One chair still warm.",
    imageKey: "work-ink-3",
    imageAlt: "An ink drawing of a kitchen table",
  },
  {
    _id: "artwork.waiting-room",
    title: "Waiting Room",
    slug: "waiting-room",
    artistId: "artist.sam",
    year: 2023,
    medium: "Ink drawing",
    featured: false,
    imageKey: "work-ink-1",
    imageAlt: "An ink illustration of people waiting",
  },
  {
    _id: "artwork.grocery-line",
    title: "Grocery Line",
    slug: "grocery-line",
    artistId: "artist.sam",
    year: 2025,
    medium: "Ink drawing",
    featured: false,
    imageKey: "work-ink-2",
    imageAlt: "An ink drawing of a checkout line",
  },

  // River — interior collages
  {
    _id: "artwork.ferry-kitchen",
    title: "Ferry Kitchen",
    slug: "ferry-kitchen",
    artistId: "artist.river",
    year: 2025,
    medium: "Collage on board",
    featured: false,
    description: "Ticket stubs and a seed catalogue page for the sink.",
    imageKey: "work-collage-1",
    imageAlt: "A cut-paper collage of an interior room",
  },
  {
    _id: "artwork.catalogue-bedroom",
    title: "Catalogue Bedroom",
    slug: "catalogue-bedroom",
    artistId: "artist.river",
    year: 2024,
    medium: "Cut-paper collage",
    featured: false,
    imageKey: "work-collage-2",
    imageAlt: "A collage assembled from printed paper scraps",
  },
  {
    _id: "artwork.bulletin-hall",
    title: "Bulletin Hall",
    slug: "bulletin-hall",
    artistId: "artist.river",
    year: 2026,
    medium: "Collage",
    featured: false,
    imageKey: "work-collage-1",
    imageAlt: "A paper collage suggesting a hallway",
  },
  {
    _id: "artwork.ticket-parlour",
    title: "Ticket Parlour",
    slug: "ticket-parlour",
    artistId: "artist.river",
    year: 2023,
    medium: "Cut-paper collage",
    featured: false,
    description: "Ferry tickets as floorboards. Nothing glued until the third move.",
    imageKey: "work-collage-2",
    imageAlt: "A collage of tickets and catalogue pages",
  },

  // Hannah — shoreline oils + winter interiors
  {
    _id: "artwork.north-shore-morning",
    title: "North Shore Morning",
    slug: "north-shore-morning",
    artistId: "artist.hannah",
    year: 2025,
    medium: "Oil on canvas",
    dimensions: "40 × 50 cm",
    featured: true,
    description: "Tide out, wind in. Painted before the fog lifted.",
    imageKey: "work-paint-1",
    imageAlt: "An oil painting of a shoreline under grey light",
  },
  {
    _id: "artwork.red-sky-cove",
    title: "Red Sky Cove",
    slug: "red-sky-cove",
    artistId: "artist.hannah",
    year: 2024,
    medium: "Oil on linen",
    featured: false,
    imageKey: "work-paint-2",
    imageAlt: "A painting of coastal weather at dusk",
  },
  {
    _id: "artwork.tide-line",
    title: "Tide Line",
    slug: "tide-line",
    artistId: "artist.hannah",
    year: 2026,
    medium: "Oil on canvas",
    featured: false,
    imageKey: "work-paint-1",
    imageAlt: "An oil painting of wet sand and sky",
  },
  {
    _id: "artwork.kettle-window",
    title: "Kettle Window",
    slug: "kettle-window",
    artistId: "artist.hannah",
    year: 2025,
    medium: "Oil on panel",
    featured: false,
    description: "The kitchen after the shoreline. Same palette, quieter subject.",
    imageKey: "work-paint-3",
    imageAlt: "A painting of a kitchen interior near a window",
  },
  {
    _id: "artwork.winter-chair",
    title: "Winter Chair",
    slug: "winter-chair",
    artistId: "artist.hannah",
    year: 2023,
    medium: "Oil on canvas",
    featured: false,
    imageKey: "work-paint-3",
    imageAlt: "A painting of a chair facing a window",
  },
  {
    _id: "artwork.february-table",
    title: "February Table",
    slug: "february-table",
    artistId: "artist.hannah",
    year: 2024,
    medium: "Acrylic on panel",
    featured: false,
    imageKey: "work-paint-2",
    imageAlt: "A painting of a table in winter light",
  },

  // Kofi — harbour nights
  {
    _id: "artwork.after-the-boats",
    title: "After the Boats",
    slug: "after-the-boats",
    artistId: "artist.kofi",
    year: 2025,
    medium: "Gelatin silver print",
    dimensions: "20 × 25 cm",
    featured: false,
    description: "Harbour empty. Engines stopped. Silver still wet.",
    imageKey: "work-photo-1",
    imageAlt: "A black and white photograph of a harbour at night",
  },
  {
    _id: "artwork.two-am-pier",
    title: "2 a.m. Pier",
    slug: "2-am-pier",
    artistId: "artist.kofi",
    year: 2024,
    medium: "Gelatin silver print",
    featured: false,
    imageKey: "work-photo-2",
    imageAlt: "A night photograph of a pier and water",
  },
  {
    _id: "artwork.engine-room-light",
    title: "Engine Room Light",
    slug: "engine-room-light",
    artistId: "artist.kofi",
    year: 2026,
    medium: "Film photograph",
    featured: false,
    imageKey: "work-photo-1",
    imageAlt: "A darkroom print of industrial harbour light",
  },
  {
    _id: "artwork.empty-slip",
    title: "Empty Slip",
    slug: "empty-slip",
    artistId: "artist.kofi",
    year: 2023,
    medium: "Gelatin silver print",
    featured: false,
    imageKey: "work-photo-2",
    imageAlt: "A black and white photo of an empty boat slip",
  },

  // Sable — blankets + weavings
  {
    _id: "artwork.bed-blanket-green",
    title: "Bed Blanket, Green",
    slug: "bed-blanket-green",
    artistId: "artist.sable",
    year: 2025,
    medium: "Wool textile, plant dye",
    dimensions: "200 × 150 cm",
    featured: false,
    description: "Local fleece. A green that failed twice before it stuck.",
    imageKey: "work-textile-1",
    imageAlt: "A woven wool blanket folded on a bed",
  },
  {
    _id: "artwork.bed-blanket-rust",
    title: "Bed Blanket, Rust",
    slug: "bed-blanket-rust",
    artistId: "artist.sable",
    year: 2024,
    medium: "Woven wool, plant dye",
    featured: false,
    imageKey: "work-textile-2",
    imageAlt: "A rust-coloured textile draped over a chair",
  },
  {
    _id: "artwork.marsh-weaving",
    title: "Marsh Weaving",
    slug: "marsh-weaving",
    artistId: "artist.sable",
    year: 2026,
    medium: "Wall weaving, wool",
    featured: false,
    imageKey: "work-textile-3",
    imageAlt: "A wall hanging woven from dyed wool",
  },
  {
    _id: "artwork.harbour-cloth",
    title: "Harbour Cloth",
    slug: "harbour-cloth",
    artistId: "artist.sable",
    year: 2023,
    medium: "Fibre, plant dye",
    featured: false,
    imageKey: "work-textile-1",
    imageAlt: "A textile piece with muted plant-dyed colours",
  },
  {
    _id: "artwork.loom-panel",
    title: "Loom Panel",
    slug: "loom-panel",
    artistId: "artist.sable",
    year: 2025,
    medium: "Wool weave",
    featured: false,
    description: "Stiff enough to hang. Soft enough that hands still want it.",
    imageKey: "work-textile-3",
    imageAlt: "A woven panel hung on a studio wall",
  },

  // Noor — shoreline jewelry
  {
    _id: "artwork.fundy-ring",
    title: "Fundy Ring",
    slug: "fundy-ring",
    artistId: "artist.noor",
    year: 2025,
    medium: "Sterling silver, beach stone",
    featured: false,
    description: "A stone that already looked finished. Set for dishwashing hands.",
    imageKey: "work-jewel-1",
    imageAlt: "A silver ring with a beach stone",
  },
  {
    _id: "artwork.tide-pendant",
    title: "Tide Pendant",
    slug: "tide-pendant",
    artistId: "artist.noor",
    year: 2024,
    medium: "Sterling silver, beach stone",
    featured: false,
    imageKey: "work-jewel-2",
    imageAlt: "A pendant with a smooth beach stone",
  },
  {
    _id: "artwork.shoreline-band",
    title: "Shoreline Band",
    slug: "shoreline-band",
    artistId: "artist.noor",
    year: 2026,
    medium: "Gold jewelry, Fundy stone",
    featured: false,
    imageKey: "work-jewel-1",
    imageAlt: "A simple band set with a small stone",
  },
  {
    _id: "artwork.bead-earrings",
    title: "Bead Earrings",
    slug: "bead-earrings",
    artistId: "artist.noor",
    year: 2023,
    medium: "Sterling silver and bead",
    featured: false,
    imageKey: "work-jewel-2",
    imageAlt: "A pair of silver earrings with small beads",
  },

  // Ellis — backyard birds + supper table
  {
    _id: "artwork.chickadee-edition",
    title: "Chickadee Edition",
    slug: "chickadee-edition",
    artistId: "artist.ellis",
    year: 2025,
    medium: "Linocut on cotton rag",
    dimensions: "Edition of 18",
    featured: true,
    description: "Backyard bird, cut twice. Ink still wet in the corners.",
    imageKey: "work-print-1",
    imageAlt: "A linocut print of a bird on paper",
  },
  {
    _id: "artwork.crow-proof",
    title: "Crow Proof",
    slug: "crow-proof",
    artistId: "artist.ellis",
    year: 2024,
    medium: "Linocut print",
    featured: false,
    imageKey: "work-print-2",
    imageAlt: "A printmaking proof of a crow",
  },
  {
    _id: "artwork.supper-table",
    title: "Supper Table",
    slug: "supper-table",
    artistId: "artist.ellis",
    year: 2026,
    medium: "Linocut on cotton rag",
    featured: false,
    description: "Plates, forks, and the empty chair. Edition of twelve.",
    imageKey: "work-print-3",
    imageAlt: "A linocut of a set table",
  },
  {
    _id: "artwork.bread-board",
    title: "Bread Board",
    slug: "bread-board",
    artistId: "artist.ellis",
    year: 2025,
    medium: "Etching on paper",
    featured: false,
    imageKey: "work-print-1",
    imageAlt: "A print of a bread board and knife",
  },
  {
    _id: "artwork.sparrow-run",
    title: "Sparrow Run",
    slug: "sparrow-run",
    artistId: "artist.ellis",
    year: 2023,
    medium: "Linocut",
    featured: false,
    imageKey: "work-print-2",
    imageAlt: "A small linocut of a sparrow",
  },

  // Wren — garden sculptures + mixed panels
  {
    _id: "artwork.marsh-stake",
    title: "Marsh Stake",
    slug: "marsh-stake",
    artistId: "artist.wren",
    year: 2025,
    medium: "Driftwood and steel sculpture",
    dimensions: "140 cm high",
    featured: false,
    description: "Weighted for Tantramar wind. Stood in mud until it earned a wall.",
    imageKey: "work-sculpt-1",
    imageAlt: "A garden sculpture of wood and metal outdoors",
  },
  {
    _id: "artwork.garden-post",
    title: "Garden Post",
    slug: "garden-post",
    artistId: "artist.wren",
    year: 2024,
    medium: "Carved driftwood sculpture",
    featured: false,
    imageKey: "work-sculpt-2",
    imageAlt: "A tall wooden sculpture in a garden",
  },
  {
    _id: "artwork.dump-panel",
    title: "Dump Panel",
    slug: "dump-panel",
    artistId: "artist.wren",
    year: 2026,
    medium: "Mixed media assemblage",
    featured: false,
    description: "Wood, steel, and a transfer from a photograph found at the dump.",
    imageKey: "work-mixed-1",
    imageAlt: "A mixed-media panel with wood and photographic elements",
  },
  {
    _id: "artwork.barn-assemblage",
    title: "Barn Assemblage",
    slug: "barn-assemblage",
    artistId: "artist.wren",
    year: 2023,
    medium: "Mixed media on board",
    featured: false,
    imageKey: "work-mixed-2",
    imageAlt: "An assemblage of wood, metal, and paper on a board",
  },
  {
    _id: "artwork.wind-weight",
    title: "Wind Weight",
    slug: "wind-weight",
    artistId: "artist.wren",
    year: 2025,
    medium: "Steel and driftwood sculpture",
    featured: false,
    imageKey: "work-sculpt-1",
    imageAlt: "A heavy outdoor sculpture of steel and wood",
  },

  // Maeve — bed runners + wall hangings
  {
    _id: "artwork.island-runner",
    title: "Island Runner",
    slug: "island-runner",
    artistId: "artist.maeve",
    year: 2025,
    medium: "Wool textile, plant dye",
    dimensions: "180 × 40 cm",
    featured: false,
    description: "A bed runner dyed the week the lupins went over.",
    imageKey: "work-textile-1",
    imageAlt: "A woven textile runner on a bed",
  },
  {
    _id: "artwork.guest-cloth",
    title: "Guest Cloth",
    slug: "guest-cloth",
    artistId: "artist.maeve",
    year: 2024,
    medium: "Woven wool, plant dye",
    featured: false,
    imageKey: "work-textile-2",
    imageAlt: "A soft woven cloth folded on linen",
  },
  {
    _id: "artwork.summerside-hanging",
    title: "Summerside Hanging",
    slug: "summerside-hanging",
    artistId: "artist.maeve",
    year: 2026,
    medium: "Wall weaving, wool",
    featured: false,
    imageKey: "work-textile-3",
    imageAlt: "A wall hanging of dyed wool",
  },
  {
    _id: "artwork.hedgerow-panel",
    title: "Hedgerow Panel",
    slug: "hedgerow-panel",
    artistId: "artist.maeve",
    year: 2023,
    medium: "Fibre, plant dye",
    featured: false,
    imageKey: "work-textile-1",
    imageAlt: "A fibre panel with plant-dyed colour",
  },
  {
    _id: "artwork.strait-weave",
    title: "Strait Weave",
    slug: "strait-weave",
    artistId: "artist.maeve",
    year: 2025,
    medium: "Wool weave",
    featured: false,
    description: "Stiff enough to hang. Soft enough that hands still want it.",
    imageKey: "work-textile-3",
    imageAlt: "A woven panel hung on a wall",
  },

  // Tessa — salt-glaze jars + garden pots
  {
    _id: "artwork.salt-jar",
    title: "Salt Jar",
    slug: "salt-jar",
    artistId: "artist.tessa",
    year: 2025,
    medium: "Salt-glaze stoneware",
    dimensions: "32 × 18 cm",
    featured: false,
    description: "Flour jar. Surface like the Strait after a blow.",
    imageKey: "work-ceramic-1",
    imageAlt: "A tall ceramic jar with a weathered glaze",
  },
  {
    _id: "artwork.bean-crock",
    title: "Bean Crock",
    slug: "bean-crock",
    artistId: "artist.tessa",
    year: 2024,
    medium: "Salt-glaze pottery",
    featured: false,
    imageKey: "work-ceramic-2",
    imageAlt: "A ceramic crock on a wooden shelf",
  },
  {
    _id: "artwork.garden-pot-east",
    title: "Garden Pot, East",
    slug: "garden-pot-east",
    artistId: "artist.tessa",
    year: 2026,
    medium: "Hand-built stoneware",
    featured: false,
    imageKey: "work-ceramic-3",
    imageAlt: "A garden pot photographed outdoors",
  },
  {
    _id: "artwork.trap-shed-bowl",
    title: "Trap Shed Bowl",
    slug: "trap-shed-bowl",
    artistId: "artist.tessa",
    year: 2023,
    medium: "Stoneware, salt glaze",
    featured: false,
    imageKey: "work-ceramic-4",
    imageAlt: "A ceramic bowl with a salt glaze",
  },
  {
    _id: "artwork.montague-urn",
    title: "Montague Urn",
    slug: "montague-urn",
    artistId: "artist.tessa",
    year: 2025,
    medium: "Wheel-thrown stoneware",
    featured: false,
    imageKey: "work-ceramic-2",
    imageAlt: "A wheel-thrown ceramic urn",
  },

  // Owen — chairs + cutting boards
  {
    _id: "artwork.ice-storm-chair",
    title: "Ice Storm Chair",
    slug: "ice-storm-chair",
    artistId: "artist.owen",
    year: 2025,
    medium: "Salvaged maple",
    featured: false,
    description: "Three coats of oil. Built from storm-fallen maple.",
    imageKey: "work-wood-3",
    imageAlt: "A wooden chair in a workshop",
  },
  {
    _id: "artwork.brook-stool",
    title: "Brook Stool",
    slug: "brook-stool",
    artistId: "artist.owen",
    year: 2024,
    medium: "Maple timber",
    featured: false,
    imageKey: "work-wood-3",
    imageAlt: "A small wooden stool",
  },
  {
    _id: "artwork.honest-board",
    title: "Honest Board",
    slug: "honest-board",
    artistId: "artist.owen",
    year: 2026,
    medium: "Maple cutting board",
    featured: false,
    description: "One oil coat. Meant to scar.",
    imageKey: "work-wood-2",
    imageAlt: "A wooden cutting board on a counter",
  },
  {
    _id: "artwork.corner-board",
    title: "Corner Board",
    slug: "corner-board",
    artistId: "artist.owen",
    year: 2023,
    medium: "Walnut and maple",
    featured: false,
    imageKey: "work-wood-1",
    imageAlt: "A cutting board of mixed woods",
  },
  {
    _id: "artwork.porch-chair",
    title: "Porch Chair",
    slug: "porch-chair",
    artistId: "artist.owen",
    year: 2025,
    medium: "Salvaged maple",
    featured: false,
    imageKey: "work-wood-3",
    imageAlt: "A wooden chair outdoors",
  },

  // Isla — harbour nights + whale-watch weather
  {
    _id: "artwork.twillingate-night",
    title: "Twillingate Night",
    slug: "twillingate-night",
    artistId: "artist.isla",
    year: 2025,
    medium: "Oil on canvas",
    dimensions: "50 × 60 cm",
    featured: false,
    description: "Harbour after the day boats. Iceberg still deciding.",
    imageKey: "work-paint-1",
    imageAlt: "An oil painting of a harbour at night",
  },
  {
    _id: "artwork.day-boat-in",
    title: "Day Boat In",
    slug: "day-boat-in",
    artistId: "artist.isla",
    year: 2024,
    medium: "Oil on linen",
    featured: false,
    imageKey: "work-paint-2",
    imageAlt: "A painting of boats in a harbour",
  },
  {
    _id: "artwork.whale-watch-weather",
    title: "Whale-Watch Weather",
    slug: "whale-watch-weather",
    artistId: "artist.isla",
    year: 2026,
    medium: "Oil on panel",
    featured: false,
    description: "Painted before the light left. No second pass.",
    imageKey: "work-paint-1",
    imageAlt: "An oil sketch of coastal weather",
  },
  {
    _id: "artwork.berg-shadow",
    title: "Berg Shadow",
    slug: "berg-shadow",
    artistId: "artist.isla",
    year: 2023,
    medium: "Oil on canvas",
    featured: false,
    imageKey: "work-paint-3",
    imageAlt: "A painting of ice and water",
  },
  {
    _id: "artwork.cold-studio",
    title: "Cold Studio",
    slug: "cold-studio",
    artistId: "artist.isla",
    year: 2025,
    medium: "Acrylic on panel",
    featured: false,
    imageKey: "work-paint-2",
    imageAlt: "A painting of a cold studio interior",
  },

  // Priya — market stalls + apartment windows
  {
    _id: "artwork.saturday-market",
    title: "Saturday Market",
    slug: "saturday-market",
    artistId: "artist.priya",
    year: 2025,
    medium: "Ink illustration on paper",
    featured: true,
    description: "Before the good vegetables are gone.",
    imageKey: "work-ink-1",
    imageAlt: "An ink drawing of a market stall",
  },
  {
    _id: "artwork.wrong-sunset",
    title: "Wrong Sunset",
    slug: "wrong-sunset",
    artistId: "artist.priya",
    year: 2024,
    medium: "Ink drawing",
    featured: false,
    imageKey: "work-ink-2",
    imageAlt: "An ink drawing of apartment windows",
  },
  {
    _id: "artwork.bus-transfer",
    title: "Bus Transfer",
    slug: "bus-transfer",
    artistId: "artist.priya",
    year: 2026,
    medium: "Ink illustration",
    featured: false,
    imageKey: "work-ink-3",
    imageAlt: "An ink illustration of people at a bus stop",
  },
  {
    _id: "artwork.laundry-line",
    title: "Laundry Line",
    slug: "laundry-line",
    artistId: "artist.priya",
    year: 2023,
    medium: "Ink drawing",
    featured: false,
    imageKey: "work-ink-1",
    imageAlt: "An ink drawing of a laundry line",
  },
  {
    _id: "artwork.corner-store",
    title: "Corner Store",
    slug: "corner-store",
    artistId: "artist.priya",
    year: 2025,
    medium: "Ink illustration on paper",
    featured: false,
    imageKey: "work-ink-2",
    imageAlt: "An ink drawing of a corner store",
  },

  // Malik — street markets + night buses
  {
    _id: "artwork.seaport-stall",
    title: "Seaport Stall",
    slug: "seaport-stall",
    artistId: "artist.malik",
    year: 2025,
    medium: "Gelatin silver print",
    dimensions: "20 × 25 cm",
    featured: true,
    description: "Market light that is unkind on purpose.",
    imageKey: "work-photo-1",
    imageAlt: "A black and white photograph of a market stall",
  },
  {
    _id: "artwork.night-bus-7",
    title: "Night Bus 7",
    slug: "night-bus-7",
    artistId: "artist.malik",
    year: 2024,
    medium: "Film photograph",
    featured: false,
    imageKey: "work-photo-2",
    imageAlt: "A night photograph through a bus window",
  },
  {
    _id: "artwork.after-tourists",
    title: "After Tourists",
    slug: "after-tourists",
    artistId: "artist.malik",
    year: 2026,
    medium: "Gelatin silver print",
    featured: false,
    imageKey: "work-photo-1",
    imageAlt: "A street photograph after the crowd left",
  },
  {
    _id: "artwork.stop-fourteen",
    title: "Stop Fourteen",
    slug: "stop-fourteen",
    artistId: "artist.malik",
    year: 2023,
    medium: "Film photograph",
    featured: false,
    imageKey: "work-photo-2",
    imageAlt: "A photograph of a bus stop at night",
  },
  {
    _id: "artwork.vendor-hands",
    title: "Vendor Hands",
    slug: "vendor-hands",
    artistId: "artist.malik",
    year: 2025,
    medium: "Gelatin silver print",
    featured: false,
    imageKey: "work-photo-1",
    imageAlt: "A close photograph of hands at a market",
  },

  // Cass — harbour steel + drift forms
  {
    _id: "artwork.harbour-turn",
    title: "Harbour Turn",
    slug: "harbour-turn",
    artistId: "artist.cass",
    year: 2025,
    medium: "Steel sculpture",
    dimensions: "160 cm high",
    featured: true,
    description: "Weighted for Fundy wind. Stands where trucks turn around.",
    imageKey: "work-sculpt-1",
    imageAlt: "A steel sculpture outdoors near a harbour",
  },
  {
    _id: "artwork.bolt-post",
    title: "Bolt Post",
    slug: "bolt-post",
    artistId: "artist.cass",
    year: 2024,
    medium: "Welded steel sculpture",
    featured: false,
    imageKey: "work-sculpt-2",
    imageAlt: "A welded steel sculpture",
  },
  {
    _id: "artwork.drift-form",
    title: "Drift Form",
    slug: "drift-form",
    artistId: "artist.cass",
    year: 2026,
    medium: "Driftwood sculpture",
    featured: false,
    description: "Quieter than the steel. Still heavy enough that the wind loses.",
    imageKey: "work-sculpt-2",
    imageAlt: "A driftwood sculpture on the ground",
  },
  {
    _id: "artwork.tide-weight",
    title: "Tide Weight",
    slug: "tide-weight",
    artistId: "artist.cass",
    year: 2023,
    medium: "Steel and timber sculpture",
    featured: false,
    imageKey: "work-sculpt-1",
    imageAlt: "A heavy sculpture of steel and wood",
  },
  {
    _id: "artwork.digby-stake",
    title: "Digby Stake",
    slug: "digby-stake",
    artistId: "artist.cass",
    year: 2025,
    medium: "Harbour steel sculpture",
    featured: false,
    imageKey: "work-sculpt-1",
    imageAlt: "A steel stake sculpture by the water",
  },

  // Yuki — river-stone set + everyday bands
  {
    _id: "artwork.river-ring",
    title: "River Ring",
    slug: "river-ring",
    artistId: "artist.yuki",
    year: 2025,
    medium: "Sterling silver, river stone",
    featured: false,
    description: "A stone that already looked finished.",
    imageKey: "work-jewel-1",
    imageAlt: "A silver ring with a river stone",
  },
  {
    _id: "artwork.everyday-band",
    title: "Everyday Band",
    slug: "everyday-band",
    artistId: "artist.yuki",
    year: 2024,
    medium: "Sterling silver band",
    featured: false,
    imageKey: "work-jewel-1",
    imageAlt: "A simple silver band",
  },
  {
    _id: "artwork.sweater-pendant",
    title: "Sweater Pendant",
    slug: "sweater-pendant",
    artistId: "artist.yuki",
    year: 2026,
    medium: "Sterling silver, beach stone",
    featured: false,
    imageKey: "work-jewel-2",
    imageAlt: "A pendant that sits flat under a sweater",
  },
  {
    _id: "artwork.dishwater-ring",
    title: "Dishwater Ring",
    slug: "dishwater-ring",
    artistId: "artist.yuki",
    year: 2023,
    medium: "Gold jewelry",
    featured: false,
    description: "Survives dishwashing. That is the brief.",
    imageKey: "work-jewel-1",
    imageAlt: "A durable gold ring",
  },
  {
    _id: "artwork.two-stone-studs",
    title: "Two-Stone Studs",
    slug: "two-stone-studs",
    artistId: "artist.yuki",
    year: 2025,
    medium: "Silver and stone bead",
    featured: false,
    imageKey: "work-jewel-2",
    imageAlt: "A pair of silver stud earrings",
  },

  // Rowan — ticket collages + linocut runs
  {
    _id: "artwork.ferry-stub-room",
    title: "Ferry Stub Room",
    slug: "ferry-stub-room",
    artistId: "artist.rowan",
    year: 2025,
    medium: "Collage on board",
    featured: false,
    description: "Tickets that have already been somewhere.",
    imageKey: "work-collage-1",
    imageAlt: "A collage made from tickets and stubs",
  },
  {
    _id: "artwork.bus-pass-kitchen",
    title: "Bus Pass Kitchen",
    slug: "bus-pass-kitchen",
    artistId: "artist.rowan",
    year: 2024,
    medium: "Cut-paper collage",
    featured: false,
    imageKey: "work-collage-2",
    imageAlt: "A cut-paper collage of a kitchen",
  },
  {
    _id: "artwork.small-linocut-run",
    title: "Small Linocut Run",
    slug: "small-linocut-run",
    artistId: "artist.rowan",
    year: 2026,
    medium: "Linocut on cotton rag",
    dimensions: "Edition of 12",
    featured: false,
    imageKey: "work-print-1",
    imageAlt: "A small linocut print on paper",
  },
  {
    _id: "artwork.kettle-edition",
    title: "Kettle Edition",
    slug: "kettle-edition",
    artistId: "artist.rowan",
    year: 2023,
    medium: "Linocut print",
    featured: false,
    imageKey: "work-print-3",
    imageAlt: "A linocut of a kettle",
  },
  {
    _id: "artwork.stub-parlour",
    title: "Stub Parlour",
    slug: "stub-parlour",
    artistId: "artist.rowan",
    year: 2025,
    medium: "Collage",
    featured: false,
    imageKey: "work-collage-1",
    imageAlt: "A collage suggesting a parlour from paper stubs",
  },
];

/** Portrait and work images used by the catalog (and shared by editorial pages). */
export const catalogImagePlan = [
  ["portrait-mira", unsplash("photo-1544005313-94ddf0286df2"), "portrait-mira.jpg"],
  ["portrait-emile", unsplash("photo-1524504388940-b1c1722653e1"), "portrait-emile.jpg"],
  ["portrait-jo", unsplash("photo-1472099645785-5658abf4ff4e"), "portrait-jo.jpg"],
  ["portrait-sam", unsplash("photo-1507003211169-0a1dd7228f2d"), "portrait-sam.jpg"],
  ["portrait-river", unsplash("photo-1534528741775-53994a69daeb"), "portrait-river.jpg"],
  ["portrait-hannah", unsplash("photo-1438761681033-6461ffad8d80"), "portrait-hannah.jpg"],
  ["portrait-kofi", unsplash("photo-1506794778202-cad84cf45f1d"), "portrait-kofi.jpg"],
  ["portrait-sable", unsplash("photo-1580489944761-15a19d654956"), "portrait-sable.jpg"],
  ["portrait-noor", unsplash("photo-1573496359142-b8d87734a5a2"), "portrait-noor.jpg"],
  ["portrait-ellis", unsplash("photo-1500648767791-00dcc994a43e"), "portrait-ellis.jpg"],
  ["portrait-wren", unsplash("photo-1517841905240-472988babdf9"), "portrait-wren.jpg"],
  ["portrait-maeve", unsplash("photo-1494790108377-be9c29b29330"), "portrait-maeve.jpg"],
  ["portrait-tessa", unsplash("photo-1544005313-94ddf0286df2"), "portrait-tessa.jpg"],
  ["portrait-owen", unsplash("photo-1500648767791-00dcc994a43e"), "portrait-owen.jpg"],
  ["portrait-isla", unsplash("photo-1534528741775-53994a69daeb"), "portrait-isla.jpg"],
  ["portrait-priya", unsplash("photo-1573496359142-b8d87734a5a2"), "portrait-priya.jpg"],
  ["portrait-malik", unsplash("photo-1506794778202-cad84cf45f1d"), "portrait-malik.jpg"],
  ["portrait-cass", unsplash("photo-1507003211169-0a1dd7228f2d"), "portrait-cass.jpg"],
  ["portrait-yuki", unsplash("photo-1580489944761-15a19d654956"), "portrait-yuki.jpg"],
  ["portrait-rowan", unsplash("photo-1438761681033-6461ffad8d80"), "portrait-rowan.jpg"],

  ["work-ceramic-1", unsplash("photo-1578749556568-bc2c40e68b61"), "work-ceramic-1.jpg"],
  ["work-ceramic-2", unsplash("photo-1565193566173-7a0ee3dbe261"), "work-ceramic-2.jpg"],
  ["work-ceramic-3", unsplash("photo-1610701596007-11502861dcfa"), "work-ceramic-3.jpg"],
  ["work-ceramic-4", unsplash("photo-1581783342308-f792dbdd27c5"), "work-ceramic-4.jpg"],

  ["work-glass-1", unsplash("photo-1602143407151-7111542de6e8"), "work-glass-1.jpg"],
  ["work-glass-2", unsplash("photo-1601925260368-ae2f83cf8b7f"), "work-glass-2.jpg"],
  ["work-glass-3", unsplash("photo-1513558161293-cdaf765ed2fd"), "work-glass-3.jpg"],

  ["work-wood-1", unsplash("photo-1416879595882-3373a0480b5b"), "work-wood-1.jpg"],
  ["work-wood-2", unsplash("photo-1556910103-1c02745aae4d"), "work-wood-2.jpg"],
  ["work-wood-3", unsplash("photo-1595428774223-ef52624120d2"), "work-wood-3.jpg"],

  ["work-ink-1", unsplash("photo-1455390582262-044cdead277a"), "work-ink-1.jpg"],
  ["work-ink-2", unsplash("photo-1513364776144-60967b0f800f"), "work-ink-2.jpg"],
  ["work-ink-3", unsplash("photo-1513694203232-719a280e022f"), "work-ink-3.jpg"],

  ["work-collage-1", unsplash("photo-1460661419201-fd4cecdf8a8b"), "work-collage-1.jpg"],
  ["work-collage-2", unsplash("photo-1579783902614-a3fb3927b6a5"), "work-collage-2.jpg"],

  ["work-paint-1", unsplash("photo-1578301978693-85fa9c0320b9"), "work-paint-1.jpg"],
  ["work-paint-2", unsplash("photo-1541961017774-22349e4a1262"), "work-paint-2.jpg"],
  ["work-paint-3", unsplash("photo-1579783901586-d88db74b4fe4"), "work-paint-3.jpg"],

  ["work-photo-1", unsplash("photo-1507525428034-b723cf961d3e"), "work-photo-1.jpg"],
  ["work-photo-2", unsplash("photo-1469474968028-56623f02e42e"), "work-photo-2.jpg"],

  ["work-textile-1", unsplash("photo-1558171813-4c088753af8f"), "work-textile-1.jpg"],
  ["work-textile-2", unsplash("photo-1528459801416-a9e53bbf4e17"), "work-textile-2.jpg"],
  ["work-textile-3", unsplash("photo-1616486338812-3dadae4b4ace"), "work-textile-3.jpg"],

  ["work-jewel-1", unsplash("photo-1515562141207-7a88fb7ce338"), "work-jewel-1.jpg"],
  ["work-jewel-2", unsplash("photo-1605100804763-247f67b3557e"), "work-jewel-2.jpg"],

  ["work-print-1", unsplash("photo-1577083552431-6e5fd01aa342"), "work-print-1.jpg"],
  ["work-print-2", unsplash("photo-1460661419201-fd4cecdf8a8b"), "work-print-2.jpg"],
  ["work-print-3", unsplash("photo-1513364776144-60967b0f800f"), "work-print-3.jpg"],

  ["work-sculpt-1", unsplash("photo-1544531586-fde5298cdd40"), "work-sculpt-1.jpg"],
  ["work-sculpt-2", unsplash("photo-1544967082-d9d25d867d66"), "work-sculpt-2.jpg"],

  ["work-mixed-1", unsplash("photo-1561214115-f2f134cc4912"), "work-mixed-1.jpg"],
  ["work-mixed-2", unsplash("photo-1558611848-73f7eb4001a1"), "work-mixed-2.jpg"],
];
